#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location / {

      proxy_pass  http://127.0.0.1:__PORT__/;
      include     proxy_params_no_auth;

      # Disable buffering for large uploads
      proxy_request_buffering off;
      client_max_body_size 0;
}

location /console/ {
      proxy_pass  http://127.0.0.1:__PORT_CONSOLE__;
#      include     proxy_params_no_auth;
      }
}
